"""Narrow capabilities required by retained application use cases."""

from typing import Protocol

from roadmap.domain.aggregates import Issue, Milestone, Project
from roadmap.domain.types import EntityId, Timestamp

from .contracts import GitSnapshot, IssueQueryRecord, MigrationPlan, MigrationResult


class Clock(Protocol):
    def now(self) -> Timestamp: ...


class LoadIssue(Protocol):
    def load_issue(self, issue_id: EntityId) -> Issue | None: ...


class SaveIssue(Protocol):
    def save_issue(self, issue: Issue) -> None: ...


class LoadMilestone(Protocol):
    def load_milestone(self, milestone_id: EntityId) -> Milestone | None: ...


class SaveMilestone(Protocol):
    def save_milestone(self, milestone: Milestone) -> None: ...


class LoadProject(Protocol):
    def load_project(self, project_id: EntityId) -> Project | None: ...


class SaveProject(Protocol):
    def save_project(self, project: Project) -> None: ...


class UnitOfWork(Protocol):
    def commit(self) -> None: ...
    def rollback(self) -> None: ...


class ProjectionMaintenance(Protocol):
    def refresh(self, changed_ids: tuple[EntityId, ...]) -> None: ...
    def rebuild(self) -> None: ...


class InspectLocalGit(Protocol):
    def inspect_local_git(self) -> GitSnapshot: ...


class ReadIssueRecords(Protocol):
    """Canonical issue records, optionally accelerated by a projection."""

    def list_issue_records(self) -> tuple[IssueQueryRecord, ...]: ...
    def load_issue_record(self, issue_id: EntityId) -> IssueQueryRecord | None: ...
    def next_milestone_id(self) -> EntityId | None: ...


class CurrentIdentity(Protocol):
    def current_identity(self) -> str | None: ...


class AssigneeDirectory(Protocol):
    def canonical_assignee(self, assignee: str) -> str | None: ...


class IssueUnitOfWork(Protocol):
    projection_stale: bool

    def __enter__(self) -> "IssueUnitOfWork": ...
    def __exit__(self, exc_type, exc, traceback) -> None: ...
    def list_issues(self) -> tuple[Issue, ...]: ...
    def load_issue(self, issue_id: EntityId) -> Issue | None: ...
    def load_milestone(self, milestone_id: EntityId) -> Milestone | None: ...
    def save_issue(self, issue: Issue) -> None: ...
    def delete_issue(self, issue_id: EntityId) -> bool: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...


class IssueUnitOfWorkFactory(Protocol):
    def create(self) -> IssueUnitOfWork: ...


class PlanningUnitOfWork(IssueUnitOfWork, Protocol):
    def __enter__(self) -> "PlanningUnitOfWork": ...
    def list_milestones(self) -> tuple[Milestone, ...]: ...
    def list_projects(self) -> tuple[Project, ...]: ...
    def load_project(self, project_id: EntityId) -> Project | None: ...
    def save_milestone(self, milestone: Milestone) -> None: ...
    def save_project(self, project: Project) -> None: ...
    def delete_milestone(self, milestone_id: EntityId) -> bool: ...
    def delete_project(self, project_id: EntityId) -> bool: ...


class PlanningUnitOfWorkFactory(Protocol):
    def create(self) -> PlanningUnitOfWork: ...


class WorkspaceMigrationPort(Protocol):
    """Explicit one-time workspace schema transition owned by a boundary."""

    def preflight(self) -> MigrationPlan: ...
    def execute(self, fingerprint: str) -> MigrationResult: ...
