"""Structural contract for the legacy GitHub services retained until Phase 11."""

from typing import Any, Protocol

from roadmap.core.domain import Issue


class GitHubBackendInterface(Protocol):
    def authenticate(self) -> bool: ...
    def get_issues(self) -> dict[str, Any]: ...
    def get_issue(self, issue_id: str) -> Any: ...
    def create_issue(self, issue: Issue) -> str: ...
    def update_issue(self, issue_id: str, issue: Issue) -> bool: ...
    def close_issue(self, issue_id: str) -> bool: ...
    def list_repositories(self) -> list[str]: ...
    def validate_credentials(self, token: str) -> bool: ...
