#!/usr/bin/env python3
"""Analyze coverage JSON and print least-covered files.

This script consumes the JSON output generated by pytest-cov (e.g. coverage.json)
and reports files with the lowest statement coverage percentages.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Report least-covered files from a pytest-cov JSON report.",
    )
    parser.add_argument(
        "--coverage-file",
        default="coverage.json",
        help="Path to coverage JSON file (default: coverage.json)",
    )
    parser.add_argument(
        "--top",
        type=int,
        default=20,
        help="Number of files to show (default: 20)",
    )
    parser.add_argument(
        "--min-statements",
        type=int,
        default=1,
        help="Only include files with at least this many statements (default: 1)",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    coverage_path = Path(args.coverage_file)
    if not coverage_path.exists():
        print(f"Coverage file not found: {coverage_path}")
        return 1

    try:
        data = json.loads(coverage_path.read_text())
    except json.JSONDecodeError as exc:
        print(f"Invalid JSON in coverage file {coverage_path}: {exc}")
        return 1

    files = data.get("files", {})
    rows: list[tuple[str, float, int, int]] = []
    for file_path, payload in files.items():
        summary = payload.get("summary", {})
        statements = int(summary.get("num_statements", 0) or 0)
        if statements < args.min_statements:
            continue
        missing = int(summary.get("missing_lines", 0) or 0)
        coverage_pct = float(summary.get("percent_covered", 0.0) or 0.0)
        rows.append((file_path, coverage_pct, missing, statements))

    rows.sort(key=lambda row: (row[1], -row[2], -row[3], row[0]))

    print("TOP_LEAST_COVERED_FILES")
    for index, (file_path, coverage_pct, missing, statements) in enumerate(
        rows[: args.top],
        start=1,
    ):
        print(
            f"{index:2d}. {file_path}"
            f"|coverage={coverage_pct:.1f}%"
            f"|missing={missing}"
            f"|statements={statements}"
        )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
